### ISSUE TITLE
Brainstem Expectations are not cancellable

### ISSUE THREAD

**Issue by juanca** [mavenlink/brainstem-js#90]
Seems like an expectation only returns a promise. It would be nice to automatically inject an `abort` method (just like an XHR).

**Comment by juanca** [comment]
This seems to be reoccurring when doing integration tests. 

I'll probably do this sometime soon (Friday project?)

/cc @naganowl @racerpeter

**Comment by juanca** [comment]
Example stack trace:

```
TypeError: xhrs[trackKey].abort is not a function
    at Object.fetch (webpack:///~/brainstem-redux/bin/index.js:1460:0 <- frontend/react-specs.js:113356:82)
    at Object.fetchStories (webpack:///frontend/features/time-entry-widget/action-creators/stories-autocompleter.js:31:29 <- frontend/react-specs.js:115096:47)
    at Object.fetchStories (webpack:///frontend/features/time-entry-widget/containers/stories-autocompleter.jsx:14:28 <- frontend/react-specs.js:115040:48)
    at StoriesAutocompleter.onInputFocus (webpack:///frontend/components/autocompleters/stories-autocompleter/stories-autocompleter.jsx:91:15 <- frontend/react-specs.js:105491:19)
    at Object.invokeGuardedCallback [as invokeGuardedCallbackWithCatch] (webpack:///~/react-dom/lib/ReactErrorUtils.js:26:0 <- frontend/react-specs.js:63489:6)
    at executeDispatch (webpack:///~/react-dom/lib/EventPluginUtils.js:83:0 <- frontend/react-specs.js:63315:22)
    at Object.executeDispatchesInOrder (webpack:///~/react-dom/lib/EventPluginUtils.js:108:0 <- frontend/react-specs.js:63340:6)
    at executeDispatchesAndRelease (webpack:///~/react-dom/lib/EventPluginHub.js:43:0 <- frontend/react-specs.js:62759:23)
    at executeDispatchesAndReleaseSimulated (webpack:///~/react-dom/lib/EventPluginHub.js:51:0 <- frontend/react-specs.js:62767:11)
    at forEachAccumulated (webpack:///~/react-dom/lib/forEachAccumulated.js:26:0 <- frontend/react-specs.js:63634:9)
     Expected "<input type="text" value="" autocomplete="off" role="combobox" aria-autocomplete="list" aria-owns="react-autowhatever-1" aria-expanded="false" aria-haspopup="false" class="stories-autocompleter__input___SyXQQ" id="stories-autocompleter-input-iw5nif7q" placeholder="Select or search for a task">" to have value of "🤘 Punch Me in the Skull 🤘"
    at Object.<anonymous> (webpack:///frontend/features/time-entry-widget/index-spec.jsx:334:58 <- frontend/react-specs.js:122749:60)
```

**Comment by juanca** [comment]
Fixed @ https://github.com/mavenlink/brainstem-js/pull/91

**Comment by juanca** [comment]
Looks like cached objects are missing an `abort` method as well. Reopening since both of these solutions should use each other.
